title: Colin has a development blog
author: colin-pm
email: colinmca242@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my space for writing about cool things I'm playing around with
  or working on.  On this page you will see a variety of things I'm
  interested in that's embedded Linux, security, and IoT related. If
  anything interests you, please feel free to reach out!
  
# Site configurations
theme: minima

# social links
github_username:  colin-pm # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
